"""Store backend-related constants used by the extended validation widget."""
from __future__ import annotations

import re
from pathlib import Path

NATURAL_SPLIT_PATTERN = re.compile(r"(\d+)")
INVALID_FILENAME_PATTERN = re.compile(r'[<>:"/\\|?*\x00-\x1F]+')
FRAME_NUMBER_PATTERN = re.compile(r"^\d+$")
CACHE_DIR = Path(__file__).resolve().parent / ".cache"
ANALYSIS_CACHE_DIR = CACHE_DIR / "analysis_payloads"
DETAIL_CACHE_DIR = CACHE_DIR / "detail_payloads"
ANALYSIS_CACHE_VERSION = "v42_confidence_risk_score"
SCORE_CACHE_DB = CACHE_DIR / "score_cache.sqlite3"
IMAGE_CACHE_SIZE = 256
SQLITE_BATCH_SIZE = 900
MISMATCH_WAIT_TIMEOUT = 0.05

METRIC_STATUS_ACTIVE = "active"
METRIC_STATUS_AUXILIARY = "auxiliary"
METRIC_STATUS_LEGACY = "legacy"

MASK_SUPERVISED_SCORE_WEIGHTS = {
    "soft_dice": 0.20,
    "soft_iou": 0.15,
    "ssim": 0.15,
    "dice": 0.20,
    "iou": 0.10,
    "hausdorff_term": 0.12,
    "centroid_term": 0.08,
}

POINT_SUPERVISED_SCORE_WEIGHTS = {
    "f1": 0.40,
    "localization": 0.30,
    "count_term": 0.30,
}

MASK_AGREEMENT_SCORE_WEIGHTS = {
    "soft_dice": 0.20,
    "soft_iou": 0.15,
    "ssim": 0.15,
    "dice": 0.20,
    "iou": 0.15,
    "hausdorff_term": 0.10,
    "centroid_term": 0.05,
}

POINT_AGREEMENT_SCORE_WEIGHTS = {
    "f1": 0.50,
    "localization": 0.30,
    "count_agreement": 0.20,
}

BCE_SCORE_CAP = 1.0

INTER_MODEL_POLYGON_SCORE_WEIGHTS = {
    "iou": 0.40,
    "dice": 0.40,
    "bce": 0.20,
}

INTER_MODEL_POINT_SCORE_WEIGHTS = {
    "precision": 0.20,
    "recall": 0.20,
    "f1": 0.40,
    "localization": 0.20,
}



MODEL_CONFIDENCE_UNCERTAIN_DELTA = 0.10
POINT_CONFIDENCE_NEIGHBOR_RADIUS = 3
POLYGON_SUPPORT_THRESHOLD = 0.05
POINT_SUPPORT_THRESHOLD = 0.05
MODEL_RISK_UNCERTAINTY_THRESHOLD = 0.40
MODEL_RISK_TOP_UNCERTAIN_FRACTION = 0.10
MODEL_RISK_WEIGHT_FRACTION = 0.50
MODEL_RISK_WEIGHT_TOP = 0.30
MODEL_RISK_WEIGHT_CLUSTER = 0.20
POLYGON_CONFIDENCE_SUMMARY_WEIGHTED = "weighted"
POLYGON_CONFIDENCE_SUMMARY_CORE = "core"
POLYGON_CONFIDENCE_SUMMARY_OPTIONS = (
    POLYGON_CONFIDENCE_SUMMARY_WEIGHTED,
    POLYGON_CONFIDENCE_SUMMARY_CORE,
)

POLYGON_CONFIDENCE_HYSTERESIS_LOW_RATIO = 0.6
POLYGON_CONFIDENCE_HYSTERESIS_FLOOR = 0.08

POLYGON_CONFIDENCE_PROPOSAL_PEAK_RATIO = 0.65
POLYGON_CONFIDENCE_PROPOSAL_PEAK_FLOOR = 0.14
POLYGON_CONFIDENCE_PROPOSAL_MEAN_FLOOR = 0.10
POLYGON_CONFIDENCE_PROPOSAL_MIN_AREA = 3
POLYGON_CONFIDENCE_COMPLETION_WEAK_RATIO = 0.70
POLYGON_CONFIDENCE_COMPLETION_LOW_RATIO = 0.22
POLYGON_CONFIDENCE_COMPLETION_BRIDGE_RADIUS = 2
POLYGON_CONFIDENCE_COMPLETION_AXIS_RATIO = 1.6
POLYGON_CONFIDENCE_COMPLETION_MAJOR_SCALE = 2
POLYGON_CONFIDENCE_PREPROC_GAUSSIAN_SIGMA = 0.35
POLYGON_CONFIDENCE_PREPROC_MEDIAN_RADIUS = 0
POLYGON_CONFIDENCE_LOCAL_NORMALIZATION_RADIUS = 9
POLYGON_CONFIDENCE_LOCAL_NORMALIZATION_STRENGTH = 0.45
POLYGON_CONFIDENCE_ELONGATED_VERTICAL_RADIUS = 5
POLYGON_CONFIDENCE_ELONGATED_HORIZONTAL_RADIUS = 1
POLYGON_CONFIDENCE_ELONGATED_MIN_ASPECT_RATIO = 2.2
POLYGON_CONFIDENCE_ELONGATED_MIN_AREA = 6
POLYGON_CONFIDENCE_DOMINANT_MIN_AREA = 12
POLYGON_CONFIDENCE_DOMINANT_MIN_MEAN_PROBABILITY = 0.52
POLYGON_CONFIDENCE_DOMINANT_MIN_ASPECT_RATIO = 3.0
POLYGON_CONFIDENCE_DOMINANT_MIN_EXTENT = 0.72
POLYGON_CONFIDENCE_DOMINANT_LARGE_AREA = 64
POLYGON_CONFIDENCE_DOMINANT_LOCK_RADIUS = 1
POLYGON_CONFIDENCE_LARGE_POLYGON_LOW_SCALE = 0.78
POLYGON_CONFIDENCE_LARGE_POLYGON_MIN_AREA = 18
POLYGON_CONFIDENCE_LARGE_POLYGON_MIN_MAJOR_SPAN = 10
POLYGON_CONFIDENCE_LARGE_POLYGON_MIN_EXTENT = 0.38
POLYGON_CONFIDENCE_LARGE_POLYGON_MIN_ASPECT_RATIO = 1.6
POLYGON_CONFIDENCE_LARGE_POLYGON_BAND_EXPAND = 3
POLYGON_CONFIDENCE_LARGE_POLYGON_ROI_PADDING = 4
POLYGON_CONFIDENCE_LARGE_POLYGON_SEED_LOW_SCALE = 0.58
POLYGON_CONFIDENCE_LARGE_POLYGON_MAJOR_CLOSE_RADIUS = 4
POLYGON_CONFIDENCE_LARGE_POLYGON_MINOR_CLOSE_RADIUS = 1
POLYGON_CONFIDENCE_LARGE_POLYGON_BARRIER_DELTA = 0.08
POLYGON_CONFIDENCE_LARGE_POLYGON_BARRIER_COVERAGE_MIN = 0.78
POLYGON_CONFIDENCE_SMALL_LOW_SCALE = 0.90
POLYGON_CONFIDENCE_SMALL_HIGH_SCALE = 0.90
POLYGON_CONFIDENCE_SMALL_MAX_AREA = 256
POLYGON_CONFIDENCE_ADAPTIVE_RADIUS = 9
POLYGON_CONFIDENCE_ADAPTIVE_LOW_OFFSET = 0.015
POLYGON_CONFIDENCE_ADAPTIVE_HIGH_OFFSET = 0.05
POLYGON_CONFIDENCE_SEPARATION_CORE_MIN_AREA = 2
POLYGON_CONFIDENCE_SEPARATION_ROI_PADDING = 2
POLYGON_CONFIDENCE_SEPARATION_BOUNDARY_LOW_WEIGHT = 0.55
POLYGON_CONFIDENCE_SEPARATION_BOUNDARY_CONTRAST_WEIGHT = 0.25
POLYGON_CONFIDENCE_SEPARATION_BOUNDARY_UNCERTAINTY_WEIGHT = 0.20
POLYGON_CONFIDENCE_SEPARATION_BARRIER_THRESHOLD = 0.48
POLYGON_CONFIDENCE_SEPARATION_BARRIER_DILATE_RADIUS = 0
POLYGON_CONFIDENCE_SEPARATION_BRIDGE_PROBABILITY_MAX = 0.42
POLYGON_CONFIDENCE_SEPARATION_BRIDGE_BARRIER_THRESHOLD = 0.52
POLYGON_CONFIDENCE_MERGE_IOU_THRESHOLD = 0.25
POLYGON_CONFIDENCE_MERGE_DISTANCE = 2
POLYGON_CONFIDENCE_ENABLE_WATERSHED = True
POLYGON_CONFIDENCE_WATERSHED_SEED_MIN_AREA = 2
POLYGON_CONFIDENCE_HOLE_PROBABILITY_SCALE = 0.90
POLYGON_CONFIDENCE_HOLE_PROBABILITY_MAX = 0.30
POLYGON_CONFIDENCE_HOLE_MIN_AREA = 4
POLYGON_CONFIDENCE_SPILL_LARGE_AREA_FRACTION = 0.12
POLYGON_CONFIDENCE_SPILL_LARGE_EXTENT = 0.72
POLYGON_CONFIDENCE_SPILL_LOW_TEXTURE_MAX = 0.06
POLYGON_CONFIDENCE_SPILL_TRIM_DELTA = 0.04
POLYGON_CONFIDENCE_SPILL_BOUNDARY_SEPARATION_MAX = 0.10
POLYGON_CONFIDENCE_SPILL_PEAK_MARGIN_MAX = 0.10
POLYGON_CONFIDENCE_SPILL_RIBBON_ASPECT_MIN = 3.0
POLYGON_CONFIDENCE_SPILL_BORDER_COVERAGE_MIN = 0.90
POLYGON_CONFIDENCE_SPILL_MEAN_PROBABILITY_MAX = 0.82
POLYGON_CONFIDENCE_SPILL_CROSS_AXIS_MAX = 0.18
POLYGON_CONFIDENCE_SPILL_PROMINENCE_MIN = 0.035
POLYGON_CONFIDENCE_SPILL_STRONG_AXIS_COVERAGE_MIN = 0.55
POLYGON_CONFIDENCE_SPILL_STRONG_AREA_FRACTION_MIN = 0.22
POLYGON_CONFIDENCE_BOUNDARY_SNAP_MIN_ASPECT = 3.0
POLYGON_CONFIDENCE_BOUNDARY_SNAP_PROFILE_QUANTILE = 0.35
POLYGON_CONFIDENCE_BOUNDARY_SNAP_MIN_DROP = 0.08
POLYGON_CONFIDENCE_BOUNDARY_SNAP_MIN_RETAINED_FRACTION = 0.65
POLYGON_CONFIDENCE_VALLEY_MINOR_COVERAGE_MIN = 0.70

POLYGON_METRIC_AUDIT = {
    "soft_dice": METRIC_STATUS_ACTIVE,
    "soft_iou": METRIC_STATUS_ACTIVE,
    "ssim": METRIC_STATUS_ACTIVE,
    "dice": METRIC_STATUS_ACTIVE,
    "iou": METRIC_STATUS_ACTIVE,
    "hausdorff_distance": METRIC_STATUS_ACTIVE,
    "centroid_distance": METRIC_STATUS_ACTIVE,
    "mae": METRIC_STATUS_AUXILIARY,
    "rmse": METRIC_STATUS_AUXILIARY,
    "precision": METRIC_STATUS_AUXILIARY,
    "recall": METRIC_STATUS_AUXILIARY,
    "count_error": METRIC_STATUS_AUXILIARY,
    "connected_component_error": METRIC_STATUS_AUXILIARY,
    "boundary_f1": METRIC_STATUS_AUXILIARY,
    "delta_connected_components": METRIC_STATUS_LEGACY,
    "break_count": METRIC_STATUS_LEGACY,
    "false_bridge_count": METRIC_STATUS_LEGACY,
    "skeleton_length_delta": METRIC_STATUS_LEGACY,
}

POINT_METRIC_AUDIT = {
    "precision_at_radius": METRIC_STATUS_ACTIVE,
    "recall_at_radius": METRIC_STATUS_ACTIVE,
    "f1_at_radius": METRIC_STATUS_ACTIVE,
    "mean_localization_error": METRIC_STATUS_ACTIVE,
    "localization_score": METRIC_STATUS_ACTIVE,
    "count_error": METRIC_STATUS_ACTIVE,
    "chamfer_score": METRIC_STATUS_AUXILIARY,
    "hausdorff_score": METRIC_STATUS_AUXILIARY,
}

FRAME_LEVEL_METRIC_AUDIT = {
    "overall_frame_score": METRIC_STATUS_ACTIVE,
    "export_priority_score": METRIC_STATUS_AUXILIARY,
    "model_model_score": METRIC_STATUS_ACTIVE,
    "disagreement_score": METRIC_STATUS_AUXILIARY,
    "model_labeled_score": METRIC_STATUS_ACTIVE,
    "labeled_best_quality": METRIC_STATUS_AUXILIARY,
    "labeled_mean_quality": METRIC_STATUS_AUXILIARY,
    "model_confidence": METRIC_STATUS_ACTIVE,
    "model_uncertain_fraction": METRIC_STATUS_ACTIVE,
    "model_point_contrast": METRIC_STATUS_AUXILIARY,
}

USE_STRICT_SUPERVISED_HEATMAP = False

EXPORT_SELECTION_MODE_COUNT = "count"
EXPORT_SELECTION_MODE_PERCENT = "percent"
EXPORT_SELECTION_MODE_PERCENTILE = "percentile"
