"""Cartograph domain: coordinates, tiles, registration contracts, local topology."""

from .coordinates import (
    GridCoordinate,
    LocalTransform,
    NominalCoordinate,
    NominalPlacementMode,
    PixelSize,
    StageCoordinate,
    TransformKind,
    Translation2D,
    regular_grid_position,
    stage_to_pixels,
)
from .errors import CartographError, GridLoadError, PlacementError, PersistenceError, RegistrationError
from .layers import LayerAligner, LayerAlignment, TopologyConstraintProvider
from .registration import (
    ConfidenceWeights,
    FeaturePairRegistrar,
    PairHint,
    PairRegistrar,
    PhasePeak,
    RegistrationBackend,
    RegistrationMethod,
    RegistrationParameters,
    RegistrationResult,
    RegistrationScore,
    RegistrationStatus,
    compute_confidence,
)
from .tiles import ImageBuffer, Tile, TileGrid
from .topology import (
    LocalBlockOptimizer,
    LocalBlockSolution,
    LocalGraph,
    LocalWindow,
    select_window,
)

__all__ = [
    "CartographError",
    "ConfidenceWeights",
    "FeaturePairRegistrar",
    "GridCoordinate",
    "GridLoadError",
    "ImageBuffer",
    "LayerAligner",
    "LayerAlignment",
    "LocalBlockOptimizer",
    "LocalBlockSolution",
    "LocalGraph",
    "LocalTransform",
    "LocalWindow",
    "NominalCoordinate",
    "NominalPlacementMode",
    "PairHint",
    "PairRegistrar",
    "PersistenceError",
    "PhasePeak",
    "PixelSize",
    "PlacementError",
    "RegistrationBackend",
    "RegistrationError",
    "RegistrationMethod",
    "RegistrationParameters",
    "RegistrationResult",
    "RegistrationScore",
    "RegistrationStatus",
    "StageCoordinate",
    "Tile",
    "TileGrid",
    "TopologyConstraintProvider",
    "TransformKind",
    "Translation2D",
    "compute_confidence",
    "regular_grid_position",
    "select_window",
    "stage_to_pixels",
]
