"""Universal virtualized frame matrix and pluggable thumbnail cache."""

from .cache import ThumbnailCacheCoordinator
from .factory import ThumbnailStoreFactory
from .models import (
    LodBand,
    LodPolicy,
    MatrixAggregate,
    MatrixAssetRef,
    MatrixBounds,
    MatrixConfig,
    MatrixItem,
    MatrixOrientation,
    MatrixSelection,
    MatrixSession,
    MatrixViewportRequest,
    MatrixViewportResult,
)
from .ports import MatrixAssetSource, MatrixDataSource, MatrixLayerRenderer, MatrixLayout, MatrixLodPolicy
from .storage import (
    CorruptEntry,
    InvalidationSelector,
    StoreCapability,
    StoreFull,
    StoreNamespace,
    StorePolicy,
    StoreReadOnly,
    StoreStats,
    StoreUnavailable,
    ThumbnailKey,
    ThumbnailRecord,
    ThumbnailStore,
    UnsupportedOperation,
)

__all__ = [
    "CorruptEntry",
    "InvalidationSelector",
    "LodBand",
    "LodPolicy",
    "MatrixAggregate",
    "MatrixAssetRef",
    "MatrixAssetSource",
    "MatrixBounds",
    "MatrixConfig",
    "MatrixDataSource",
    "MatrixItem",
    "MatrixLayerRenderer",
    "MatrixLayout",
    "MatrixLodPolicy",
    "MatrixOrientation",
    "MatrixSelection",
    "MatrixSession",
    "MatrixViewportRequest",
    "MatrixViewportResult",
    "StoreCapability",
    "StoreFull",
    "StoreNamespace",
    "StorePolicy",
    "StoreReadOnly",
    "StoreStats",
    "StoreUnavailable",
    "ThumbnailCacheCoordinator",
    "ThumbnailKey",
    "ThumbnailRecord",
    "ThumbnailStore",
    "ThumbnailStoreFactory",
    "UnsupportedOperation",
]
