from contour.infrastructure.cif_opencif import NativeCifPayload

def load_cif_file(path: str, continue_on_error: bool = True) -> NativeCifPayload: ...
def library_version() -> str: ...
def library_name() -> str: ...
